### PR TITLE
mp x6

### PR DESCRIPTION
**Pull request by Anexes**
All class mp x6

### CODE REVIEW

**Comment by seiyria** [comment]
:+1:

**Comment by AscendedGravity** [comment]
👌

**Comment by Anexes** [comment]
@seiyria Sorry, forgot to test it. I'm seeing vector monsters with 12k mp, but monster has 30 mp per level, so they should have 30x200=6,000 mp. I have no idea why. Do vector monsters get double stats or something?

**Comment by seiyria** [comment]
Remember that you get MP per int (which they get) + they also get some gear, which adds on to that.

**Comment by Anexes** [comment]
@seiyria By default, [profession](https://github.com/IdleLands/IdleLands/blob/master/src/core/base/profession.js#L13-L19) doesn't give any mp whatsoever, and [monster](https://github.com/IdleLands/IdleLands/blob/master/src/core/professions/Monster.js) doesn't give mp for any stats, it only gives 5 base mp per level (which I upped to 30.) Am I missing something?

**Comment by seiyria** [comment]
not sure then. checked out the generator and I don't see any math happening. same with the stat calculator. that's pretty weird.

**Comment by Anexes** [comment]
@seiyria Ok, it looks like everybody is getting the right amount of mp from their stats, but the base amount of mp they get for their levels is doubled for some reason. It says, for instance, 3600 mp in their statCache (18 mp/lvl for fighters, at level 200,) but it's actually adding 7200 to _mp. I only changed the mp/stat values, so I think this was already a thing.

**Comment by Anexes** [comment]
@seiyria Ah, I think [this](https://github.com/IdleLands/IdleLands/blob/master/src/shared/stat-calculator.js#L181-L188) is it. It's adding `prof.baseMpPerLevel * level` and `this.stat(player, 'mp')`, but the latter includes the former, so it's getting added twice. Same is true for hp.

**Comment by seiyria** [comment]
d'oh. that would make sense. I'm not sure which reduction makes sense, but feel free to take away from somewhere to make the math work!

**Comment by Anexes** [comment]
@seiyria Hoo boy, if I'm understanding half of this, stat-calculator needs a rewrite. It looks like [this](https://github.com/IdleLands/IdleLands/blob/master/src/shared/stat-calculator.js#L188) (which is defined [here](https://github.com/IdleLands/IdleLands/blob/master/src/shared/stat-calculator.js#L130-L148),) doesn't account for the mp gained through the profession's mp/stat values. It gets the `baseMpPerLevel` through `_baseStat()`, along with any mp gained from items, achievements, etc., but not the mp/stat values. Those values are added up, multiplied by any modifiers from profession, achievements, etc., and that's handed back to the mp function and the mp/stat values are added to that.

I checked explorer and found that it reduced my int by ~20%, which isn't too far off, but it's definitely not correct. If it's supposed to be reducing my stats by 25%, then it's working at 80% efficiency (20/25=0.8,) which I can only assume means it's only affecting 80% of my int. Somehow 20% of my int isn't affected by the multiplier. That's definitely more than I get from my profession (about 21x more,) so there are clearly other values that aren't being properly included in the calculations, but I have no idea which values those are.

**Comment by Anexes** [comment]
@seiyria I tell you what, let's put this PR through, since it doesn't seem to be the cause of the problem, and fixing the stats problem can be its own thing.

**Comment by seiyria** [comment]
yeah, that's fine with me.

**Pull request merged**
