### PR TITLE
Refactor: UIService

### PR DESCRIPTION
**Pull request by majoferenc**
Implements functionality proposed by #79

### CODE REVIEW

**Comment by seiyria** [comment]
This looks nice so far, but the idea was to refactor all badge-related code from the sidebar into this service. This would also include the chat message count, premium free roll badge, quest complete badge, unsynced settings badge, and the scrolls badge for gear. Let me know if that's ok!

**Comment by seiyria** [comment]
Looks good, thanks! I'll have to test it out but it should be fine.

**Comment by majoferenc** [comment]
Thanks, of course, I was also wondering about mongodb setup. I can create docker images for mongodb, server and also frontend, if you want, so mlab will be not needed.

**Comment by seiyria** [comment]
That could be helpful. You'd have to find the version of Mongo that actually works (it looks like my local is 4.0.9, but I'm not sure if it will work without issue). As long as it's just a wrapper (ie, not required, because I personally just have everything set up) then I'm in support of that.

Please know though that it will take me a while to understand how it works, so I might have more questions at that time if you go through with it!

**Pull request merged**
