### PR TITLE
Add donate all resources button on Materials & Scrolls page

### PR DESCRIPTION
**Pull request by Rovastus**
Implements functionality proposed by #120

### CODE REVIEW

**Comment by seiyria** [comment]
Can you share a picture of what this looks like?

**Comment by Rovastus** [comment]
image

**Comment by seiyria** [comment]
Sorry I didn't specify in the issue, but can this be made into a dropdown (similar to the dropdown on the equipment page) where this action is present? It would fit there much better.

**Comment by Rovastus** [comment]
Something like this ? 
image

**Comment by seiyria** [comment]
No, the triple dot dropdown on the top right.

**Comment by Rovastus** [comment]
So, something like this ? 
image

**Comment by seiyria** [comment]
Yes, that would be fine!

**Comment by Rovastus** [comment]
Ok, also should the triple dot dropdown show up only if user have a guild ? Or this condition should only apply on action button in dropdown.

**Comment by seiyria** [comment]
Yes, it makes sense if the triple dot is hidden by people not having a guild.

**Comment by Rovastus** [comment]
image

**Comment by boozledorf** [comment]
Should the option be grayed out if there are no resources to donate or is that too much?  Other than that, it looks good

**Comment by seiyria** [comment]
I don't think there's a need for that. Just fix up the code based on Travis output and it'll be good to go!

**Pull request merged**
